import os
import json

BASE_DIR = r'g:\My Drive\Flash Cards'
DECKS_DIR = os.path.join(BASE_DIR, 'decks', 'Countries-Capital')
dataset_path = os.path.join(DECKS_DIR, 'data.json')

# Currency data for all 196 countries
currency_map = {
    "af": {"currency": "Afghan Afghani", "symbol": "؋", "code": "AFN"},
    "al": {"currency": "Albanian Lek", "symbol": "L", "code": "ALL"},
    "dz": {"currency": "Algerian Dinar", "symbol": "دج", "code": "DZD"},
    "ad": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "ao": {"currency": "Angolan Kwanza", "symbol": "Kz", "code": "AOA"},
    "ag": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "ar": {"currency": "Argentine Peso", "symbol": "$", "code": "ARS"},
    "am": {"currency": "Armenian Dram", "symbol": "֏", "code": "AMD"},
    "au": {"currency": "Australian Dollar", "symbol": "A$", "code": "AUD"},
    "at": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "az": {"currency": "Azerbaijani Manat", "symbol": "₼", "code": "AZN"},
    "bs": {"currency": "Bahamian Dollar", "symbol": "B$", "code": "BSD"},
    "bh": {"currency": "Bahraini Dinar", "symbol": ".د.ب", "code": "BHD"},
    "bd": {"currency": "Bangladeshi Taka", "symbol": "৳", "code": "BDT"},
    "bb": {"currency": "Barbadian Dollar", "symbol": "Bds$", "code": "BBD"},
    "by": {"currency": "Belarusian Ruble", "symbol": "Br", "code": "BYN"},
    "be": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "bz": {"currency": "Belize Dollar", "symbol": "BZ$", "code": "BZD"},
    "bj": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "bt": {"currency": "Bhutanese Ngultrum", "symbol": "Nu", "code": "BTN"},
    "bo": {"currency": "Bolivian Boliviano", "symbol": "Bs.", "code": "BOB"},
    "ba": {"currency": "Bosnia-Herzegovina Mark", "symbol": "KM", "code": "BAM"},
    "bw": {"currency": "Botswana Pula", "symbol": "P", "code": "BWP"},
    "br": {"currency": "Brazilian Real", "symbol": "R$", "code": "BRL"},
    "bn": {"currency": "Brunei Dollar", "symbol": "B$", "code": "BND"},
    "bg": {"currency": "Bulgarian Lev", "symbol": "лв", "code": "BGN"},
    "bf": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "bi": {"currency": "Burundian Franc", "symbol": "Fr", "code": "BIF"},
    "cv": {"currency": "Cape Verdean Escudo", "symbol": "$", "code": "CVE"},
    "kh": {"currency": "Cambodian Riel", "symbol": "៛", "code": "KHR"},
    "cm": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "ca": {"currency": "Canadian Dollar", "symbol": "C$", "code": "CAD"},
    "cf": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "td": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "cl": {"currency": "Chilean Peso", "symbol": "$", "code": "CLP"},
    "cn": {"currency": "Chinese Yuan", "symbol": "¥", "code": "CNY"},
    "co": {"currency": "Colombian Peso", "symbol": "$", "code": "COP"},
    "km": {"currency": "Comorian Franc", "symbol": "CF", "code": "KMF"},
    "cg": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "cd": {"currency": "Congolese Franc", "symbol": "FC", "code": "CDF"},
    "cr": {"currency": "Costa Rican Colón", "symbol": "₡", "code": "CRC"},
    "hr": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "cu": {"currency": "Cuban Peso", "symbol": "$", "code": "CUP"},
    "cy": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "cz": {"currency": "Czech Koruna", "symbol": "Kč", "code": "CZK"},
    "dk": {"currency": "Danish Krone", "symbol": "kr", "code": "DKK"},
    "dj": {"currency": "Djiboutian Franc", "symbol": "Fdj", "code": "DJF"},
    "dm": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "do": {"currency": "Dominican Peso", "symbol": "RD$", "code": "DOP"},
    "ec": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "eg": {"currency": "Egyptian Pound", "symbol": "£", "code": "EGP"},
    "sv": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "gq": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "er": {"currency": "Eritrean Nakfa", "symbol": "Nfk", "code": "ERN"},
    "ee": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "sz": {"currency": "Swazi Lilangeni", "symbol": "L", "code": "SZL"},
    "et": {"currency": "Ethiopian Birr", "symbol": "Br", "code": "ETB"},
    "fj": {"currency": "Fijian Dollar", "symbol": "FJ$", "code": "FJD"},
    "fi": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "fr": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "ga": {"currency": "Central African CFA Franc", "symbol": "CFA", "code": "XAF"},
    "gm": {"currency": "Gambian Dalasi", "symbol": "D", "code": "GMD"},
    "ge": {"currency": "Georgian Lari", "symbol": "₾", "code": "GEL"},
    "de": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "gh": {"currency": "Ghanaian Cedi", "symbol": "₵", "code": "GHS"},
    "gr": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "gd": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "gt": {"currency": "Guatemalan Quetzal", "symbol": "Q", "code": "GTQ"},
    "gn": {"currency": "Guinean Franc", "symbol": "FG", "code": "GNF"},
    "gw": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "gy": {"currency": "Guyanese Dollar", "symbol": "G$", "code": "GYD"},
    "ht": {"currency": "Haitian Gourde", "symbol": "G", "code": "HTG"},
    "hn": {"currency": "Honduran Lempira", "symbol": "L", "code": "HNL"},
    "hu": {"currency": "Hungarian Forint", "symbol": "Ft", "code": "HUF"},
    "is": {"currency": "Icelandic Króna", "symbol": "kr", "code": "ISK"},
    "in": {"currency": "Indian Rupee", "symbol": "₹", "code": "INR"},
    "id": {"currency": "Indonesian Rupiah", "symbol": "Rp", "code": "IDR"},
    "ir": {"currency": "Iranian Rial", "symbol": "﷼", "code": "IRR"},
    "iq": {"currency": "Iraqi Dinar", "symbol": "ع.د", "code": "IQD"},
    "ie": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "il": {"currency": "Israeli New Shekel", "symbol": "₪", "code": "ILS"},
    "it": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "ci": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "jm": {"currency": "Jamaican Dollar", "symbol": "J$", "code": "JMD"},
    "jp": {"currency": "Japanese Yen", "symbol": "¥", "code": "JPY"},
    "jo": {"currency": "Jordanian Dinar", "symbol": "JD", "code": "JOD"},
    "kz": {"currency": "Kazakhstani Tenge", "symbol": "₸", "code": "KZT"},
    "ke": {"currency": "Kenyan Shilling", "symbol": "KSh", "code": "KES"},
    "ki": {"currency": "Australian Dollar", "symbol": "A$", "code": "AUD"},
    "kw": {"currency": "Kuwaiti Dinar", "symbol": "KD", "code": "KWD"},
    "kg": {"currency": "Kyrgyzstani Som", "symbol": "с", "code": "KGS"},
    "la": {"currency": "Lao Kip", "symbol": "₭", "code": "LAK"},
    "lv": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "lb": {"currency": "Lebanese Pound", "symbol": "ل.ل", "code": "LBP"},
    "ls": {"currency": "Lesotho Loti", "symbol": "L", "code": "LSL"},
    "lr": {"currency": "Liberian Dollar", "symbol": "L$", "code": "LRD"},
    "ly": {"currency": "Libyan Dinar", "symbol": "LD", "code": "LYD"},
    "li": {"currency": "Swiss Franc", "symbol": "Fr", "code": "CHF"},
    "lt": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "lu": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "mg": {"currency": "Malagasy Ariary", "symbol": "Ar", "code": "MGA"},
    "mw": {"currency": "Malawian Kwacha", "symbol": "MK", "code": "MWK"},
    "my": {"currency": "Malaysian Ringgit", "symbol": "RM", "code": "MYR"},
    "mv": {"currency": "Maldivian Rufiyaa", "symbol": "Rf", "code": "MVR"},
    "ml": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "mt": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "mh": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "mr": {"currency": "Mauritanian Ouguiya", "symbol": "UM", "code": "MRU"},
    "mu": {"currency": "Mauritian Rupee", "symbol": "₨", "code": "MUR"},
    "mx": {"currency": "Mexican Peso", "symbol": "$", "code": "MXN"},
    "fm": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "md": {"currency": "Moldovan Leu", "symbol": "L", "code": "MDL"},
    "mc": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "mn": {"currency": "Mongolian Tögrög", "symbol": "₮", "code": "MNT"},
    "me": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "ma": {"currency": "Moroccan Dirham", "symbol": "MAD", "code": "MAD"},
    "mz": {"currency": "Mozambican Metical", "symbol": "MT", "code": "MZN"},
    "mm": {"currency": "Myanmar Kyat", "symbol": "K", "code": "MMK"},
    "na": {"currency": "Namibian Dollar", "symbol": "N$", "code": "NAD"},
    "nr": {"currency": "Australian Dollar", "symbol": "A$", "code": "AUD"},
    "np": {"currency": "Nepalese Rupee", "symbol": "₨", "code": "NPR"},
    "nl": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "nz": {"currency": "New Zealand Dollar", "symbol": "NZ$", "code": "NZD"},
    "ni": {"currency": "Nicaraguan Córdoba", "symbol": "C$", "code": "NIO"},
    "ne": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "ng": {"currency": "Nigerian Naira", "symbol": "₦", "code": "NGN"},
    "kp": {"currency": "North Korean Won", "symbol": "₩", "code": "KPW"},
    "mk": {"currency": "North Macedonian Denar", "symbol": "ден", "code": "MKD"},
    "no": {"currency": "Norwegian Krone", "symbol": "kr", "code": "NOK"},
    "om": {"currency": "Omani Rial", "symbol": "﷼", "code": "OMR"},
    "pk": {"currency": "Pakistani Rupee", "symbol": "₨", "code": "PKR"},
    "pw": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "ps": {"currency": "Israeli New Shekel", "symbol": "₪", "code": "ILS"},
    "pa": {"currency": "Panamanian Balboa", "symbol": "B/.", "code": "PAB"},
    "pg": {"currency": "Papua New Guinean Kina", "symbol": "K", "code": "PGK"},
    "py": {"currency": "Paraguayan Guaraní", "symbol": "₲", "code": "PYG"},
    "pe": {"currency": "Peruvian Sol", "symbol": "S/.", "code": "PEN"},
    "ph": {"currency": "Philippine Peso", "symbol": "₱", "code": "PHP"},
    "pl": {"currency": "Polish Złoty", "symbol": "zł", "code": "PLN"},
    "pt": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "qa": {"currency": "Qatari Riyal", "symbol": "﷼", "code": "QAR"},
    "ro": {"currency": "Romanian Leu", "symbol": "lei", "code": "RON"},
    "ru": {"currency": "Russian Ruble", "symbol": "₽", "code": "RUB"},
    "rw": {"currency": "Rwandan Franc", "symbol": "Fr", "code": "RWF"},
    "kn": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "lc": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "vc": {"currency": "East Caribbean Dollar", "symbol": "$", "code": "XCD"},
    "ws": {"currency": "Samoan Tālā", "symbol": "T", "code": "WST"},
    "sm": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "st": {"currency": "São Tomé & Príncipe Dobra", "symbol": "Db", "code": "STN"},
    "sa": {"currency": "Saudi Riyal", "symbol": "﷼", "code": "SAR"},
    "sn": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "rs": {"currency": "Serbian Dinar", "symbol": "din", "code": "RSD"},
    "sc": {"currency": "Seychellois Rupee", "symbol": "₨", "code": "SCR"},
    "sl": {"currency": "Sierra Leonean Leone", "symbol": "Le", "code": "SLL"},
    "sg": {"currency": "Singapore Dollar", "symbol": "S$", "code": "SGD"},
    "sk": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "si": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "sb": {"currency": "Solomon Islands Dollar", "symbol": "SI$", "code": "SBD"},
    "so": {"currency": "Somali Shilling", "symbol": "Sh", "code": "SOS"},
    "za": {"currency": "South African Rand", "symbol": "R", "code": "ZAR"},
    "kr": {"currency": "South Korean Won", "symbol": "₩", "code": "KRW"},
    "ss": {"currency": "South Sudanese Pound", "symbol": "£", "code": "SSP"},
    "es": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "lk": {"currency": "Sri Lankan Rupee", "symbol": "₨", "code": "LKR"},
    "sd": {"currency": "Sudanese Pound", "symbol": "£", "code": "SDG"},
    "sr": {"currency": "Surinamese Dollar", "symbol": "$", "code": "SRD"},
    "se": {"currency": "Swedish Krona", "symbol": "kr", "code": "SEK"},
    "ch": {"currency": "Swiss Franc", "symbol": "Fr", "code": "CHF"},
    "sy": {"currency": "Syrian Pound", "symbol": "£", "code": "SYP"},
    "tw": {"currency": "New Taiwan Dollar", "symbol": "NT$", "code": "TWD"},
    "tj": {"currency": "Tajikistani Somoni", "symbol": "SM", "code": "TJS"},
    "tz": {"currency": "Tanzanian Shilling", "symbol": "Sh", "code": "TZS"},
    "th": {"currency": "Thai Baht", "symbol": "฿", "code": "THB"},
    "tl": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "tg": {"currency": "West African CFA Franc", "symbol": "CFA", "code": "XOF"},
    "to": {"currency": "Tongan Paʻanga", "symbol": "T$", "code": "TOP"},
    "tt": {"currency": "Trinidad & Tobago Dollar", "symbol": "TT$", "code": "TTD"},
    "tn": {"currency": "Tunisian Dinar", "symbol": "DT", "code": "TND"},
    "tr": {"currency": "Turkish Lira", "symbol": "₺", "code": "TRY"},
    "tm": {"currency": "Turkmenistani Manat", "symbol": "T", "code": "TMT"},
    "tv": {"currency": "Australian Dollar", "symbol": "A$", "code": "AUD"},
    "ug": {"currency": "Ugandan Shilling", "symbol": "Sh", "code": "UGX"},
    "ua": {"currency": "Ukrainian Hryvnia", "symbol": "₴", "code": "UAH"},
    "ae": {"currency": "UAE Dirham", "symbol": "د.إ", "code": "AED"},
    "gb": {"currency": "British Pound Sterling", "symbol": "£", "code": "GBP"},
    "us": {"currency": "US Dollar", "symbol": "$", "code": "USD"},
    "uy": {"currency": "Uruguayan Peso", "symbol": "$U", "code": "UYU"},
    "uz": {"currency": "Uzbekistani Som", "symbol": "so'm", "code": "UZS"},
    "vu": {"currency": "Vanuatu Vatu", "symbol": "VT", "code": "VUV"},
    "va": {"currency": "Euro", "symbol": "€", "code": "EUR"},
    "ve": {"currency": "Venezuelan Bolívar", "symbol": "Bs.F", "code": "VES"},
    "vn": {"currency": "Vietnamese Đồng", "symbol": "₫", "code": "VND"},
    "ye": {"currency": "Yemeni Rial", "symbol": "﷼", "code": "YER"},
    "zm": {"currency": "Zambian Kwacha", "symbol": "ZK", "code": "ZMW"},
    "zw": {"currency": "RTGS Dollar", "symbol": "ZWL", "code": "ZWL"},
}

# Load existing dataset
with open(dataset_path, 'r', encoding='utf-8') as f:
    country_dataset = json.load(f)

# Enrich with currency info
for item in country_dataset:
    iso = item['iso']
    curr = currency_map.get(iso, {"currency": "Unknown", "symbol": "?", "code": "???"})
    item['currency'] = curr['currency']
    item['currency_symbol'] = curr['symbol']
    item['currency_code'] = curr['code']

# Write back enriched dataset
with open(dataset_path, 'w', encoding='utf-8') as f:
    json.dump(country_dataset, f, indent=2, ensure_ascii=False)

print(f"Enriched {len(country_dataset)} countries with currency data in {dataset_path}")
